#pragma once

#define PERIPHERAL_SIZE (0x1000)
#define PERIPHERAL_BASE (0x8000)

#define EXIT_POINT (PERIPHERAL_BASE + 0x0)
#define EXIT_POINT_LENGTH (0x100)
#define EXIT_POINT_RC (EXIT_POINT + 0x0)

