#pragma once

#define PERIPHERAL_SIZE (0x1000)
#define PERIPHERAL_BASE (0x8000)

#define EXIT_POINT_BASE (PERIPHERAL_BASE + 0x0)
#define EXIT_POINT_LENGTH (0x10)
#define EXIT_POINT_RC (EXIT_POINT_BASE + 0x0)

#define TERMINAL_BASE (EXIT_POINT_BASE + EXIT_POINT_LENGTH)
#define TERMINAL_LENGTH (0x10)
#define TERMINAL_WRITE (TERMINAL_BASE + 0x0)
#define TERMINAL_READ (TERMINAL_BASE + 0x1)
